# Generated by Django 4.0.1 on 2022-01-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TienSuBenh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, null=True, unique=b'I01\n')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('MAN', 'Nam'), ('WOMAN', 'Nữ')], default='MAN', max_length=9)),
                ('birthDay', models.DateField(null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('tienSuBenhKhac', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('groupUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.groupuser')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.job')),
                ('tienSuBenh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.tiensubenh')),
            ],
        ),
    ]
