# Generated by Django 4.0.1 on 2022-02-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newphotos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
