# Generated by Django 4.0.1 on 2022-04-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_newphotos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='shortdes',
            field=models.TextField(null=True),
        ),
    ]
