# Generated by Django 4.0.1 on 2022-06-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_news_shortdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
