# Generated by Django 4.0.1 on 2022-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_topic_code_alter_topic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datlichhen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('timeCare', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
