# Generated by Django 4.0 on 2021-12-29 09:36

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
