# Generated by Django 4.0 on 2021-12-25 06:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
